### ISSUE TITLE
Dial tcp: i/o timeout when accessing CF API endpoint

### ISSUE THREAD

**Issue by ncktz** [SAP/devops-docker-cf-cli#15]
Hi,

I'm using this Docker container as part of project piper, however I'm not able to establish the connection to the CF API endpoint. There is no proxy necessary in my network and the connection works fine for all other steps/containers.

```
--- Begin library step of: dockerExecute ---
[Pipeline] timeout
Timeout set to expire in 10 sec
[Pipeline] {
[Pipeline] httpRequest

[Pipeline] }
[Pipeline] // timeout
[Pipeline] sh
+ docker ps -q
[Pipeline] isUnix
[Pipeline] sh
+ docker pull ppiper/cf-cli
Using default tag: latest

latest: Pulling from ppiper/cf-cli
Digest: sha256:4dadef1d961a1805db2b1c2d11832229962d6268e06d692a68818c5451a796ab
Status: Image is up to date for ppiper/cf-cli:latest
[Pipeline] isUnix
[Pipeline] sh
+ docker inspect -f . ppiper/cf-cli
.
[Pipeline] withDockerContainer
Jenkins seems to be running inside container 1fcdc6b6c8c2015dd746f66f714a65548e23363ca78af50b94e48d46ff2e1a2a
$ docker run -t -d -u 1000:1001 --env http_proxy --env https_proxy --env no_proxy --env HTTP_PROXY --env HTTPS_PROXY --env NO_PROXY -w /var/jenkins_home/workspace/QA --volumes-from 1fcdc6b6c8c2015dd746f66f714a65548e23363ca78af50b94e48d46ff2e1a2a -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** ppiper/cf-cli cat
$ docker top 680e99db9086cd3712ccf972d377a8d97791e868a6fce1342cd8fba6a14a3ab6 -eo pid,comm
[Pipeline] {
[Pipeline] echo
[cloudFoundryDeploy] Deploying MTA (appLibrary.mtar) with following parameters:  -f --no-confirm
[Pipeline] withCredentials
Masking supported pattern matches of $username or $password
[Pipeline] {
[Pipeline] sh

**Setting api endpoint to https://api.cf.eu10.hana.ondemand.com...

Request error: Get https://api.cf.eu10.hana.ondemand.com/v2/info: dial tcp: i/o timeout**
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.
FAILED
[Pipeline] fileExists
[Pipeline] echo
### START OF CF CLI TRACE OUTPUT ###
[Pipeline] readFile
[Pipeline] echo
REQUEST: [2019-12-08T23:40:43Z]
GET /v2/info HTTP/1.1
Host: api.cf.eu10.hana.ondemand.com
Accept: application/json
User-Agent: cf/6.46.1+4934877ec.2019-08-23 (go1.12.9; amd64 linux)

REQUEST: [2019-12-08T23:40:48Z]
GET /v2/info HTTP/1.1
Host: api.cf.eu10.hana.ondemand.com
Accept: application/json
User-Agent: cf/6.46.1+4934877ec.2019-08-23 (go1.12.9; amd64 linux)

REQUEST: [2019-12-08T23:40:53Z]
GET /v2/info HTTP/1.1
Host: api.cf.eu10.hana.ondemand.com
Accept: application/json
User-Agent: cf/6.46.1+4934877ec.2019-08-23 (go1.12.9; amd64 linux)


[Pipeline] echo
### END OF CF CLI TRACE OUTPUT ###
[Pipeline] error
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
$ docker stop --time=1 680e99db9086cd3712ccf972d377a8d97791e868a6fce1342cd8fba6a14a3ab6

$ docker rm -f 680e99db9086cd3712ccf972d377a8d97791e868a6fce1342cd8fba6a14a3ab6
[Pipeline] // withDockerContainer
[Pipeline] libraryResource
[Pipeline] echo
----------------------------------------------------------
--- An error occurred in the library step: dockerExecute
----------------------------------------------------------

The following parameters were available to the step:
***
*** to show step parameters, set verbose:true in general pipeline configuration
*** WARNING: this may reveal sensitive information. ***
***

The error was:
***
hudson.AbortException: [cloudFoundryDeploy] ERROR: The execution of the deploy command failed, see the log for details.
***
```

**Comment by fwilhe** [comment]
Hi @ncktz 

my first guess would be that there was a temporary issue somewhere which should be resolved by retrying at a later point in time. How often and at which times have you tried it?

If the issue persists: Can you access https://api.cf.eu10.hana.ondemand.com/v2/info from your Jenkins, i.e. via curl or something?

I don't think this can be fixed in the image itself.

BR

Florian

**Comment by ncktz** [comment]
Hi Florian,

Thanks for your quick response! I've seen the issue over the last days but haven't had the time to look into it in detail until today.

As an additional test, I ran the docker image directly on my local machine (docker run -i -t ppiper/cf-cli /bin/bash) and tried to connect via cf login but encountered the same issue, so I do not think it is related to Jenkins:

piper@a08bae3a1a52:~$ cf login

API endpoint> https://api.cf.eu10.hana.ondemand.com

FAILED          
Error performing request: Get https://api.cf.eu10.hana.ondemand.com/v2/info: dial tcp: i/o timeout
TIP: If you are behind a firewall and require an HTTP proxy, verify the https_proxy environment variable is correctly set. Else, check your network connection.

Best regards,
Nico

**Comment by fwilhe** [comment]
I can't reproduce this on my machine, see my log:

```
docker run -i -t ppiper/cf-cli /bin/bash
piper@c7a8c0d0bc28:~$ cf login

API endpoint> https://api.cf.eu10.hana.ondemand.com

Email> xx

Password> xx
Authenticating...
OK

Select an org (or press enter to skip):
1. ???????trial_trial
```

Can you install the cf cli on your local machine an see if you can login there?

**Comment by ncktz** [comment]
It works on my local machine:

```
$ cf login
API endpoint: https://api.cf.eu10.hana.ondemand.com

Email: xxx@xxx

Password: 
Authenticating...
OK

Select an org:
1. xxx
2. xxxtrial_trial

Org (enter to skip): 

```

**Comment by fwilhe** [comment]
Can you try to run `curl -vvv https://api.cf.eu10.hana.ondemand.com/v2/info` in the docker container on your local machine and share the output (check for confidential data in that before)?

Can you do the same from within "Script Console" in Jenkins and compare the output?

Really just guessing at this point, I don't see what the issue is.

How did you setup your Jenkins? Are you using Docker on a Windows, Mac or Linux machine?

**Comment by ncktz** [comment]
I use the Jenkins delivered with the cx-server Docker image. Docker runs on a Ubuntu VM (19.10).
Result on the docker container on my local machine:
`docker run -i -t ppiper/cf-cli /bin/bash
piper@de5b7bedb060:~$ curl -vvv https://api.cf.eu10.hana.ondemand.com/v2/info
*   Trying 3.124.222.77...
* TCP_NODELAY set
* Connected to api.cf.eu10.hana.ondemand.com (3.124.222.77) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=DE; L=Walldorf; O=SAP SE; CN=*.cf.eu10.hana.ondemand.com
*  start date: Dec  4 00:00:00 2019 GMT
*  expire date: Dec  8 12:00:00 2021 GMT
*  subjectAltName: host "api.cf.eu10.hana.ondemand.com" matched cert's "*.cf.eu10.hana.ondemand.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
> GET /v2/info HTTP/1.1
> Host: api.cf.eu10.hana.ondemand.com
> User-Agent: curl/7.52.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 631
< Content-Type: application/json;charset=utf-8
< Date: Mon, 09 Dec 2019 14:02:27 GMT
< Server: nginx
< X-Content-Type-Options: nosniff
< X-Vcap-Request-Id: xxx
< Strict-Transport-Security: max-age=31536000; includeSubDomains; preload;
< 
* Curl_http_done: called premature == 0
* Connection #0 to host api.cf.eu10.hana.ondemand.com left intact
{"name":"","build":"","support":"","version":0,"description":"Cloud Foundry at SAP Cloud Platform","authorization_endpoint":"https://login.cf.eu10.hana.ondemand.com","token_endpoint":"https://uaa.cf.eu10.hana.ondemand.com","min_cli_version":null,"min_recommended_cli_version":null,"app_ssh_endpoint":"ssh.cf.eu10.hana.ondemand.com:2222","app_ssh_host_key_fingerprint":"xxx","app_ssh_oauth_client":"ssh-proxy","doppler_logging_endpoint":"wss://doppler.cf.eu10.hana.ondemand.com:443","api_version":"2.143.0","osbapi_version":"2.15","bits_endpoint":"https://bits.cf.eu10.hana.ondemand.com"}
piper@de5b7bedb060:`

Result on Jenkins (println "curl -vvv https://api.cf.eu10.hana.ondemand.com/v2/info".execute().text):
`{"name":"","build":"","support":"","version":0,"description":"Cloud Foundry at SAP Cloud Platform","authorization_endpoint":"https://login.cf.eu10.hana.ondemand.com","token_endpoint":"https://uaa.cf.eu10.hana.ondemand.com","min_cli_version":null,"min_recommended_cli_version":null,"app_ssh_endpoint":"ssh.cf.eu10.hana.ondemand.com:2222","app_ssh_host_key_fingerprint":"xxx","app_ssh_oauth_client":"ssh-proxy","doppler_logging_endpoint":"wss://doppler.cf.eu10.hana.ondemand.com:443","api_version":"2.143.0","osbapi_version":"2.15","bits_endpoint":"https://bits.cf.eu10.hana.ondemand.com"}`

**Comment by fwilhe** [comment]
Hm, I'm out of ideas for now. Ping @marcusholl, @nevskrem, @CCFenner do you have any idea how to resolve this?

**Comment by CCFenner** [comment]
Could it be your network? Your laptop has something configured that it works, but not the containers.

**Comment by ncktz** [comment]
I had another idea and set the Docker container manually to s4sdk/docker-cf-cli and was successfully logged in and could deploy to the CF API endpoint. For this reason, it seems there is actually some issue with this Docker container.

**Comment by ncktz** [comment]
Does anyone have any more ideas or can let me know how to add a Docker Env variable(CF_DIAL_TIMEOUT ) to step CloudFoundryDeploy?

The issue stills persists, so it doesn't seem to be a temporary issue. I also tried it in four different networks but the behavior is always the same.

- If I use ppiper/cf-cli, the login already fails as specified above.
- If I use 4sdk/docker-cf-cli, I am successfully logged in and can deploy the db & nodejs module of the mta to the CF API endpoint but the last module (UI) fails again:

```
FAILED
Could not get ongoing operation: Could not get access token: auth request failed: Error performing request: Post https://login.cf.eu10.hana.ondemand.com/oauth/token: dial tcp: i/o timeout
```

Thanks a lot,
Nico

**Comment by ncktz** [comment]
As discussed offline, I tested this on AWS and the deployment worked successfully with both Docker images: s4sdk/docker-cf-cli & ppiper/docker-cf-cli . 

For this reason, I think it actually is somehow related to the setup of a local VM. I still do not understand what causes this error and why it worked without any issues in August and why the error appears at different points of the pipeline depending on the used image but we will now just continue to work with the pipeline on our AWS-Instance.

Thanks a lot for your help,
Nico

**Comment by tarun053** [comment]
How did this issue resolved ? I also have same issue
cf login gives me timeout error but CF_DIAL_TIMEOUT=15 cf login works fine
any ways to add CF_DIAL_TIMEOUT in parameters

**Comment by fwilhe** [comment]
Hi @tarun053 

The issue was resolved by not using a local vm but AWS as described in Nico's comment.

Please open a new issue with more description of what you're trying to do in what environment and what fails.

Kind regards

Florian
