### ISSUE TITLE
Invalid JSON content from server: invalid character '<' looking for beginning of value FAILED

### ISSUE THREAD

**Issue by prateekdhiman27** [SAP/devops-docker-cf-cli#27]
Hello Experts

I am trying to connect AzureDevOps Pipelines to HANA XSA system. I am using the reference provided in one of the blogs.

https://blogs.sap.com/2019/10/24/how-to-use-project-piper-docker-images-for-cicd-with-azure-devops/

I noticed that while deploying using cf-cli I get a bash error.

```
Starting: Bash
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.171.1
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
Script contents:
cf login -u "*******" -p "***" -a "*********" -o "******" -s "******" --skip-ssl-validation
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /__w/_temp/895a84ec-07bb-403d-ae3c-714ec57ca434.sh
API endpoint: https://************

Invalid JSON content from server: invalid character '<' looking for beginning of value
FAILED

##[error]Bash exited with code '1'.
Finishing: Bash
```

From AzureDevOps helps documents and GitHub issues pages , they have pointed the issue to the containers we are calling.
Any help on this is much appreciated. 

PS: I have hidden the URLs by `********`

Thanks
Prateek

**Comment by fwilhe** [comment]
This looks like your API endpoint provides some html response instead of json. Can you verify if the URL is correct? Otherwise we can't really do anything about that, as it is a configuration issue.

**Comment by prateekdhiman27** [comment]
Thanks for the hint.
